export const twilioError = {
  60701: 'Invalid request',
  60700: 'Something went wrong. Try again later',
  64015: 'Pay: `<Pay>` verb is missing a needed Parameter',
  60604: 'SendGrid Authenticated user is not authorized to send mail',
  60603: 'SendGrid maximum credits exceeded',
  60602: 'App hash can only be used with SMS channel',
  60220: 'Messages to China require use case vetting',
  60219: 'SendGrid Template does not contain required placeholders',
  60218: 'SendGrid Template is not active',
  60215: 'Max number of mailers per account reached',
  60217: `Invalid Service configuration: add an email integration before using
      the Email channel.`,
  63036: 'The specified phone number cannot be reached by RBM at this time.',
  63035: `This operation is blocked because the RBM agent has not launched and the
      recipient has not been invited and accepted the invitation to become a tester.`,
  60214: 'Call channel is not supported when using PSD2',
  64014: 'Pay: ECP/ACH requires AVSName Parameter in the <Pay> verb.',
  63034: 'Media exceeds size limit',
  64013: 'Pay: Connector does not support supplied paymentMethod attribute.',
  63033: 'Recipient blocked to receive ',
  63032: 'We cannot send this  to this user because of a WhatsApp limitation.',
  63031: 'Channels  cannot have same From and To',
  63030: 'Unsupported parameter for type of channels ',
  60213: 'A Messaging Configuration already exists for the given country',
  60212: 'Too many concurrent requests for phone number',
  63029: 'The receiver failed to download the template',
  63028: 'Number of parameters provided does not match the expected number of parameters',
  63027: 'Template does not exist for a language and locale',
  60211: 'Bucket with the given Interval already exists',
  60210: 'Max Buckets per Rate limit reached',
  60208: 'Rate limit with that UniqueName already exists',
  60207: 'Max rate limits per service reached ',
  60209: 'UniqueName format is invalid',
  63011: 'Invalid Request: Twilio encountered an error while processing your request',
  60206: `Amount' & 'Payee' params are required`,
  64012: 'Pay: Payment Gateway rejected the card.',
  64011: 'Pay: Connector does not support the requested currency.',
  64010: 'Pay: Payment Gateway rejected token creation.',
  64009: 'Pay: Twilio is no longer authorized to initiate transactions on your behalf.',
  64008: 'Pay: Payment Gateway rejected charge creation.',
  64007: 'Pay: Connector does not support creating charge.',
  64006: 'Pay: Connector does not support token type.',
  64005: 'Pay: Connector does not support tokenization.',
  64004: 'Pay: Invalid paymentConnector attribute in TwiML.',
  64003: 'Pay: Invalid charge amount.',
  64002: 'Pay: Service unavailable.',
  64001: 'Pay: Configuration Error',
  63026: 'Channel sender content flagged as spam',
  63025: 'Media already exists',
  63024: 'Invalid  recipient',
  63023: 'Channel generic error',
  63022: 'Invalid vname certificate',
  63021: 'Channel invalid content error',
  63020: 'Twilio encountered a Business Manager account error',
  63019: 'Twilio failed to download the media from the sender',
  63018: 'Rate limit exceeded for Channel',
  63017: 'Rate limit exceeded',
  63016: `Failed to send freeform  because you are outside the allowed window.
    Please use a Template.`,
  60205: 'SMS is not supported by landline phone number',
  60204: 'Service does not support this feature',
  60203: 'Max send attempts reached.',
  60202: 'Max check attempts reached',
  60101: 'Canadian number. Further authorization required.',
  60201: 'Invalid verification code',
  60200: 'Invalid parameter',
  62053: 'Interconnect: The subaccount is not authorized to access this connection.  ',
  62052: `Interconnect: This account is not a subaccount of the Interconnect
      Connection owner's account.`,
  63001: `Channel could not authenticate the request. Please see Channel
    specific error  for more information`,
  62035: 'Interconnect: No bandwidth was specified in the request',
  62034: 'Interconnect: No useful parameters provided.',
  62028: 'Interconnect: Connection expired.',
  62027: 'Interconnect: Extra MPLS parameter',
  62026: 'Interconnect: Missing MPLS carrier SID',
  62025: 'Interconnect: Invalid connection type',
  62024: 'Missing connection type',
  62023: 'Missing exchange',
  62022: 'Missing account SID',
  62021: 'IP Gateway Invalid',
  62020: 'Connection pending deletion.',
  62019: 'IP route exceeds permitted IP range',
  62018: 'Invalid IP route',
  62017: 'No IP route specified',
  62016: 'Connection not active',
  62015: 'Connection in transition',
  62014: 'Connection not ready',
  62013: 'Unable to identify account owner of connection.',
  62012: 'Connection not found.',
  62011: 'Unauthorized',
  62010: 'No authentication was provided.',
  62009: 'Account SID was not found.',
  62008: 'Bandwidth reserve is not associated with the exchange.',
  62007: 'Direct connect is not associated with the exchange.',
  62006: ' MPLS carrier is not associated with the exchange.',
  62005: ' Bandwidth reserve not found.',
  62004: 'Direct connect not found.',
  62003: 'MPLS carrier not found.',
  62002: 'Exchange not found',
  62001: 'Invalid SID',
  62000: 'Failed to write to the database.',
  61009: 'Add-ons: Could not fulfill request with available data',
  61008: 'Add-ons:  HTTP too many redirects',
  61007: 'Add-ons: Response body too large',
  61006: 'Add-ons: Add-ons unavailable for GET callbacks',
  61005: 'Add-ons: Bad request',
  61004: 'Add-ons: No results',
  61003: 'Add-ons: Requirements to invoke AddOns have not been met',
  61002: 'Add-ons: Provider could not complete request',
  61001: 'Add-ons: Request timed out',
  61000: 'Add-ons: Internal server error',
  60223: 'The delivery channel specified is currently disabled in the Verify Service settings.',
}
